name: Birthday Wisher

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 10:30 AM IST (05:00 AM UTC)
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  birthday_wisher:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.5  # Ensure this matches the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Birthday Wisher Script
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_WHATSAPP_NUMBER: ${{ secrets.TWILIO_WHATSAPP_NUMBER }}
      run: |
        python birthday_wisher.py
